import "jsr:@supabase/functions-js/edge-runtime.d.ts";
import { createClient } from "npm:@supabase/supabase-js@2.57.4";

const corsHeaders = {
  "Access-Control-Allow-Origin": "*",
  "Access-Control-Allow-Methods": "GET, POST, PUT, DELETE, OPTIONS",
  "Access-Control-Allow-Headers": "Content-Type, Authorization, X-Client-Info, Apikey",
};

async function gitlabApi(token: string, instanceUrl: string, method: string, path: string, body?: unknown) {
  const res = await fetch(`${instanceUrl}/api/v4${path}`, {
    method,
    headers: { "PRIVATE-TOKEN": token, "Content-Type": "application/json" },
    body: body ? JSON.stringify(body) : undefined,
  });
  if (!res.ok) throw new Error(`GitLab API ${res.status}: ${await res.text()}`);
  return res.json();
}

Deno.serve(async (req: Request) => {
  if (req.method === "OPTIONS") {
    return new Response(null, { status: 200, headers: corsHeaders });
  }

  try {
    const supabase = createClient(
      Deno.env.get("SUPABASE_URL")!,
      Deno.env.get("SUPABASE_SERVICE_ROLE_KEY")!
    );

    const { action, failure_id } = await req.json();
    if (!failure_id) {
      return new Response(JSON.stringify({ error: "failure_id is required" }), {
        status: 400, headers: { ...corsHeaders, "Content-Type": "application/json" },
      });
    }

    const { data: failure } = await supabase
      .from("failures")
      .select("*, projects(id, name, namespace, gitlab_project_id, default_branch)")
      .eq("id", failure_id)
      .maybeSingle();

    if (!failure) {
      return new Response(JSON.stringify({ error: "Failure not found" }), {
        status: 404, headers: { ...corsHeaders, "Content-Type": "application/json" },
      });
    }

    const gitlabProjectId = String(failure.projects?.gitlab_project_id);
    const { data: installation } = await supabase
      .from("gitlab_installations")
      .select("access_token_encrypted, gitlab_instance_url")
      .eq("gitlab_project_id", gitlabProjectId)
      .maybeSingle();

    const token = installation?.access_token_encrypted || Deno.env.get("GITLAB_TOKEN");
    const instanceUrl = installation?.gitlab_instance_url || "https://gitlab.com";

    if (!token) {
      return new Response(JSON.stringify({ error: "No GitLab token. Add your PAT in GitLab Integration > Register Project." }), {
        status: 401, headers: { ...corsHeaders, "Content-Type": "application/json" },
      });
    }

    if (action === "fetch_logs") {
      const jobs = await gitlabApi(token, instanceUrl, "GET",
        `/projects/${encodeURIComponent(gitlabProjectId)}/pipelines/${failure.pipeline_id}/jobs`);
      const failedJob = jobs.find((j: { status: string }) => j.status === "failed");
      if (!failedJob) {
        return new Response(JSON.stringify({ success: true, excerpt: "No failed job found." }), {
          headers: { ...corsHeaders, "Content-Type": "application/json" },
        });
      }
      const traceRes = await fetch(
        `${instanceUrl}/api/v4/projects/${encodeURIComponent(gitlabProjectId)}/jobs/${failedJob.id}/trace`,
        { headers: { "PRIVATE-TOKEN": token } }
      );
      const logText = traceRes.ok ? await traceRes.text() : `Could not fetch trace (${traceRes.status})`;
      const excerpt = logText.split("\n").slice(-150).join("\n").slice(-2000);
      await supabase.from("failures").update({ signal_excerpt: excerpt }).eq("id", failure_id);
      return new Response(JSON.stringify({ success: true, excerpt: excerpt.slice(-500) }), {
        headers: { ...corsHeaders, "Content-Type": "application/json" },
      });
    }

    if (action === "create_mr") {
      const fixBranch = `pipelineguardian/fix-${failure.pipeline_id}`;
      const baseBranch = failure.projects?.default_branch || "main";

      await gitlabApi(token, instanceUrl, "POST",
        `/projects/${encodeURIComponent(gitlabProjectId)}/repository/branches`,
        { branch: fixBranch, ref: baseBranch });

      const mr = await gitlabApi(token, instanceUrl, "POST",
        `/projects/${encodeURIComponent(gitlabProjectId)}/merge_requests`, {
          title: `[PipelineGuardian] Fix ${failure.error_type} in ${failure.job_name}`,
          description: `## PipelineGuardian Auto-Fix\n\n**Pipeline:** #${failure.pipeline_id}\n**Job:** ${failure.job_name} (${failure.stage})\n**Error Type:** ${failure.error_type}\n**Confidence:** ${((failure.confidence_score || 0) * 100).toFixed(0)}%\n\n### Signal\n\`\`\`\n${(failure.signal_excerpt || "").slice(-400)}\n\`\`\`\n\n---\n*Generated by PipelineGuardian via GitLab MCP*`,
          source_branch: fixBranch,
          target_branch: baseBranch,
          remove_source_branch: true,
        });

      await Promise.all([
        supabase.from("failures").update({ fix_mr_url: mr.web_url, fix_mr_id: mr.iid, status: "auto_applied" }).eq("id", failure_id),
        supabase.from("audit_logs").insert({ failure_id, agent_name: "gitlab-mr-creator", action: "mr_created", payload: { mr_iid: mr.iid, mr_url: mr.web_url } }),
      ]);

      return new Response(JSON.stringify({ success: true, mr_url: mr.web_url, mr_iid: mr.iid }), {
        headers: { ...corsHeaders, "Content-Type": "application/json" },
      });
    }

    if (action === "retry_pipeline") {
      await gitlabApi(token, instanceUrl, "POST",
        `/projects/${encodeURIComponent(gitlabProjectId)}/pipelines/${failure.pipeline_id}/retry`);
      await supabase.from("audit_logs").insert({ failure_id, agent_name: "gitlab-mr-creator", action: "pipeline_retry", payload: { pipeline_id: failure.pipeline_id } });
      return new Response(JSON.stringify({ success: true, message: "Pipeline retry triggered" }), {
        headers: { ...corsHeaders, "Content-Type": "application/json" },
      });
    }

    if (action === "lint_ci") {
      const result = await gitlabApi(token, instanceUrl, "GET",
        `/projects/${encodeURIComponent(gitlabProjectId)}/ci/lint`);
      return new Response(JSON.stringify({ success: true, valid: result.valid, errors: result.errors || [] }), {
        headers: { ...corsHeaders, "Content-Type": "application/json" },
      });
    }

    return new Response(JSON.stringify({ error: "Unknown action. Use: fetch_logs, create_mr, retry_pipeline, lint_ci" }), {
      status: 400, headers: { ...corsHeaders, "Content-Type": "application/json" },
    });
  } catch (err) {
    return new Response(JSON.stringify({ error: (err as Error).message }), {
      status: 500, headers: { ...corsHeaders, "Content-Type": "application/json" },
    });
  }
});
